# Generated by Django 3.1.4 on 2020-12-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload_passport',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='file',
            name='add_relation',
        ),
        migrations.RemoveField(
            model_name='file',
            name='age',
        ),
        migrations.RemoveField(
            model_name='file',
            name='local_government',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='file',
            name='pvc_number',
        ),
        migrations.RemoveField(
            model_name='file',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='file',
            name='state',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='upload_pvc',
        ),
        migrations.RemoveField(
            model_name='file',
            name='village_name',
        ),
    ]
