# Generated by Django 3.1.4 on 2020-12-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sex', models.TextField(blank=True)),
                ('age', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=200)),
                ('village_name', models.TextField(blank=True)),
                ('add_relation', models.TextField(blank=True)),
                ('local_government', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('pvc_number', models.CharField(max_length=200)),
            ],
        ),
    ]
